const fs = require("fs");
const path = require("path");
const { callMcpTool } = require("./rive_mcp_client.js");

const kappa = 0.5522847498307936;

async function buildOwlukoMasterHanddrawnRive() {
  console.log("===============================================================");
  console.log("  BUILDING MASTER HAND-DRAWN OWLUKO RIVE ASSET (FLAWLESS BLINK)");
  console.log("  100% Faithful to Reference, Hand-Drawn Illustrated Appeal");
  console.log("===============================================================");

  // 1. Read the calibrated v6 scene fragment generated by riv_import_svg
  const fragmentPath = path.resolve(__dirname, "../scratch/owluko_calibrated_v6.scene.json");
  if (!fs.existsSync(fragmentPath)) {
    throw new Error("Missing fragment: " + fragmentPath);
  }
  const fragment = JSON.parse(fs.readFileSync(fragmentPath, "utf-8"));
  console.log(`Loaded fragment with ${fragment.shapes.length} imported vector shapes.`);

  // 2. Define Rig Groups Hierarchy
  // Artboard 512x512, root centered at x=256, y=464
  // body_group is at root + (0, -200) -> global (256, 264)
  // head_group is at body + (0, -60) -> global (256, 204)
  // Left eye center in SVG is at (182, 162) -> relative to head: (182 - 256, 162 - 204) = (-74, -42)
  // Right eye center in SVG is at (330, 162) -> relative to head: (330 - 256, 162 - 204) = (+74, -42)
  const groups = [
    { id: "root", x: 256, y: 464 },
    { id: "shadow_group", parent: "root", x: 0, y: 0 },
    { id: "feet_group", parent: "root", x: 0, y: 0 },
    { id: "body_group", parent: "root", x: 0, y: -200 },
    { id: "head_group", parent: "body_group", x: 0, y: -60 },
    { id: "eye_l_group", parent: "head_group", x: -74, y: -42 },
    { id: "eye_r_group", parent: "head_group", x: 74, y: -42 }
  ];

  const parentMap = {
    // Ground Shadow
    p0: { parent: "shadow_group", ox: 256, oy: 464 },
    p1: { parent: "shadow_group", ox: 256, oy: 464 },

    // Left Foot (p2..p7)
    p2: { parent: "feet_group", ox: 256, oy: 464 },
    p3: { parent: "feet_group", ox: 256, oy: 464 },
    p4: { parent: "feet_group", ox: 256, oy: 464 },
    p5: { parent: "feet_group", ox: 256, oy: 464 },
    p6: { parent: "feet_group", ox: 256, oy: 464 },
    p7: { parent: "feet_group", ox: 256, oy: 464 },

    // Right Foot (p8..p13)
    p8: { parent: "feet_group", ox: 256, oy: 464 },
    p9: { parent: "feet_group", ox: 256, oy: 464 },
    p10: { parent: "feet_group", ox: 256, oy: 464 },
    p11: { parent: "feet_group", ox: 256, oy: 464 },
    p12: { parent: "feet_group", ox: 256, oy: 464 },
    p13: { parent: "feet_group", ox: 256, oy: 464 },

    // Main Body & Integrated Wings
    body_main_silhouette: { parent: "body_group", ox: 256, oy: 264 },
    p14: { parent: "body_group", ox: 256, oy: 264 },
    wing_l_crease_line: { parent: "body_group", ox: 256, oy: 264 },
    p15: { parent: "body_group", ox: 256, oy: 264 },
    p16: { parent: "body_group", ox: 256, oy: 264 },
    wing_r_crease_line: { parent: "body_group", ox: 256, oy: 264 },
    p17: { parent: "body_group", ox: 256, oy: 264 },
    belly_plush_patch: { parent: "body_group", ox: 256, oy: 264 },
    p18: { parent: "body_group", ox: 256, oy: 264 },
    p19: { parent: "body_group", ox: 256, oy: 264 },
    p20: { parent: "body_group", ox: 256, oy: 264 },

    // Facial Disk & Cheeks
    p21: { parent: "head_group", ox: 256, oy: 204 },
    facial_disk_main: { parent: "head_group", ox: 256, oy: 204 },
    p22: { parent: "head_group", ox: 256, oy: 204 },
    p23: { parent: "head_group", ox: 256, oy: 204 },
    p24: { parent: "head_group", ox: 256, oy: 204 },

    // Left Eye (eye center is exactly 182, 162)
    p25: { parent: "eye_l_group", ox: 182, oy: 162 },
    p26: { parent: "eye_l_group", ox: 182, oy: 162 },
    p27: { parent: "eye_l_group", ox: 182, oy: 162 },
    p28: { parent: "eye_l_group", ox: 182, oy: 162 },
    p29: { parent: "eye_l_group", ox: 182, oy: 162 },
    p30: { parent: "eye_l_group", ox: 182, oy: 162 },
    p31: { parent: "eye_l_group", ox: 182, oy: 162 },

    // Right Eye (eye center is exactly 330, 162)
    p32: { parent: "eye_r_group", ox: 330, oy: 162 },
    p33: { parent: "eye_r_group", ox: 330, oy: 162 },
    p34: { parent: "eye_r_group", ox: 330, oy: 162 },
    p35: { parent: "eye_r_group", ox: 330, oy: 162 },
    p36: { parent: "eye_r_group", ox: 330, oy: 162 },
    p37: { parent: "eye_r_group", ox: 330, oy: 162 },
    p38: { parent: "eye_r_group", ox: 330, oy: 162 },

    // Beak
    p39: { parent: "head_group", ox: 256, oy: 204 },
    beak_cone: { parent: "head_group", ox: 256, oy: 204 },
    p40: { parent: "head_group", ox: 256, oy: 204 },
    p41: { parent: "head_group", ox: 256, oy: 204 }
  };

  const processedShapes = [];

  for (const s of fragment.shapes) {
    const mapping = parentMap[s.id];
    if (mapping) {
      s.parent = mapping.parent;
      s.x = s.x - mapping.ox;
      s.y = s.y - mapping.oy;
    }
    processedShapes.push(s);
  }

  // Eyelid Cover Circles with Closed Smiling Contour (Exactly centered at 0, 0 in eye groups)
  const r_eye = 48.5;
  const eyelidCoverPoints = [
    { x: -r_eye, y: 0, cubic: { inRotation: 90, inDistance: r_eye * kappa, rotation: 270, outDistance: r_eye * kappa } },
    { x: 0, y: -r_eye, cubic: { inRotation: 180, inDistance: r_eye * kappa, rotation: 0, outDistance: r_eye * kappa } },
    { x: r_eye, y: 0, cubic: { inRotation: 270, inDistance: r_eye * kappa, rotation: 90, outDistance: r_eye * kappa } },
    { x: 0, y: r_eye, cubic: { inRotation: 0, inDistance: r_eye * kappa, rotation: 180, outDistance: r_eye * kappa } }
  ];

  // Sweet closed eye arc (open stroke)
  const closedEyeArc = [
    { x: -30, y: 2, cubic: { inRotation: 0, inDistance: 0, rotation: 20, outDistance: 14 } },
    { x: 0, y: 12, cubic: { inRotation: -20, inDistance: 14, rotation: -20, outDistance: 14 } },
    { x: 30, y: 2, cubic: { inRotation: 20, inDistance: 14, rotation: 0, outDistance: 0 } }
  ];

  // Left Eye Eyelid Cover & Seam
  processedShapes.push(
    {
      id: "eyelid_l_cover",
      type: "polygon",
      parent: "eye_l_group",
      x: 0,
      y: 0,
      points: eyelidCoverPoints,
      opacity: 0,
      fill: { color: "#FAF6EE" },
      stroke: { color: "#3D271A", thickness: 3.0, cap: "round", join: "round" }
    },
    {
      id: "eyelid_l_seam",
      type: "polygon",
      closed: false,
      parent: "eye_l_group",
      x: 0,
      y: 0,
      points: closedEyeArc,
      opacity: 0,
      stroke: { color: "#3D271A", thickness: 3.2, cap: "round", join: "round" }
    },
    // Right Eye Eyelid Cover & Seam
    {
      id: "eyelid_r_cover",
      type: "polygon",
      parent: "eye_r_group",
      x: 0,
      y: 0,
      points: eyelidCoverPoints,
      opacity: 0,
      fill: { color: "#FAF6EE" },
      stroke: { color: "#3D271A", thickness: 3.0, cap: "round", join: "round" }
    },
    {
      id: "eyelid_r_seam",
      type: "polygon",
      closed: false,
      parent: "eye_r_group",
      x: 0,
      y: 0,
      points: closedEyeArc,
      opacity: 0,
      stroke: { color: "#3D271A", thickness: 3.2, cap: "round", join: "round" }
    }
  );

  // 3. Fluid Animations (60 FPS, 120 frames = 2.0s seamless loop)
  const animations = [
    {
      name: "idle",
      fps: 60,
      duration: 120,
      loop: "loop",
      tracks: [
        // Body Respiration (Organic squash and stretch)
        {
          target: "body_group",
          property: "scaleY",
          keyframes: [
            { frame: 0, value: 1.0 },
            { frame: 60, value: 1.025, easing: "ease-in-out" },
            { frame: 120, value: 1.0, easing: "ease-in-out" }
          ]
        },
        {
          target: "body_group",
          property: "scaleX",
          keyframes: [
            { frame: 0, value: 1.0 },
            { frame: 60, value: 0.985, easing: "ease-in-out" },
            { frame: 120, value: 1.0, easing: "ease-in-out" }
          ]
        },
        // Head subtle follow-through harmonic lag
        {
          target: "head_group",
          property: "y",
          keyframes: [
            { frame: 0, value: -60.0 },
            { frame: 65, value: -62.5, easing: "ease-in-out" },
            { frame: 120, value: -60.0, easing: "ease-in-out" }
          ]
        },
        {
          target: "head_group",
          property: "rotation",
          keyframes: [
            { frame: 0, value: 0.0 },
            { frame: 40, value: 0.8, easing: "ease-in-out" },
            { frame: 80, value: -0.6, easing: "ease-in-out" },
            { frame: 120, value: 0.0, easing: "ease-in-out" }
          ]
        },
        // Ground Shadow subtle breathing expansion
        {
          target: "shadow_group",
          property: "scaleX",
          keyframes: [
            { frame: 0, value: 1.0 },
            { frame: 60, value: 1.03, easing: "ease-in-out" },
            { frame: 120, value: 1.0, easing: "ease-in-out" }
          ]
        },
        // Conscious Blink at frame 70..85
        {
          target: "eyelid_l_cover",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 68, value: 0 },
            { frame: 74, value: 1, easing: "ease-in" },
            { frame: 79, value: 1 },
            { frame: 84, value: 0, easing: "ease-out" },
            { frame: 120, value: 0 }
          ]
        },
        {
          target: "eyelid_l_seam",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 68, value: 0 },
            { frame: 74, value: 1, easing: "ease-in" },
            { frame: 79, value: 1 },
            { frame: 84, value: 0, easing: "ease-out" },
            { frame: 120, value: 0 }
          ]
        },
        {
          target: "eyelid_r_cover",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 68, value: 0 },
            { frame: 74, value: 1, easing: "ease-in" },
            { frame: 79, value: 1 },
            { frame: 84, value: 0, easing: "ease-out" },
            { frame: 120, value: 0 }
          ]
        },
        {
          target: "eyelid_r_seam",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 68, value: 0 },
            { frame: 74, value: 1, easing: "ease-in" },
            { frame: 79, value: 1 },
            { frame: 84, value: 0, easing: "ease-out" },
            { frame: 120, value: 0 }
          ]
        }
      ]
    },
    {
      name: "blink",
      fps: 60,
      duration: 20,
      loop: "one-shot",
      tracks: [
        {
          target: "eyelid_l_cover",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 6, value: 1, easing: "ease-in" },
            { frame: 12, value: 1 },
            { frame: 18, value: 0, easing: "ease-out" },
            { frame: 20, value: 0 }
          ]
        },
        {
          target: "eyelid_l_seam",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 6, value: 1, easing: "ease-in" },
            { frame: 12, value: 1 },
            { frame: 18, value: 0, easing: "ease-out" },
            { frame: 20, value: 0 }
          ]
        },
        {
          target: "eyelid_r_cover",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 6, value: 1, easing: "ease-in" },
            { frame: 12, value: 1 },
            { frame: 18, value: 0, easing: "ease-out" },
            { frame: 20, value: 0 }
          ]
        },
        {
          target: "eyelid_r_seam",
          property: "opacity",
          keyframes: [
            { frame: 0, value: 0 },
            { frame: 6, value: 1, easing: "ease-in" },
            { frame: 12, value: 1 },
            { frame: 18, value: 0, easing: "ease-out" },
            { frame: 20, value: 0 }
          ]
        }
      ]
    }
  ];

  // 4. Interactive State Machine
  const stateMachine = {
    name: "Owluko_SM",
    inputs: [{ name: "triggerBlink", type: "trigger" }],
    states: [
      { name: "idle_state", animation: "idle" },
      { name: "blink_state", animation: "blink" }
    ],
    transitions: [
      { from: "entry", to: "idle_state" },
      { from: "idle_state", to: "blink_state", condition: { input: "triggerBlink" } },
      { from: "blink_state", to: "idle_state", exitTimeMs: 330 }
    ]
  };

  const scene = {
    artboard: { name: "Owluko_Master", width: 512, height: 512 },
    backgroundColor: "#FAFAFA",
    groups,
    shapes: processedShapes,
    animations,
    stateMachine
  };

  // Write scene.json for live hot-reload in Rive Studio daemon
  const scenePath = path.resolve(__dirname, "../mascots/owluko/owluko_pure_vector.scene.json");
  fs.writeFileSync(scenePath, JSON.stringify(scene, null, 2));
  console.log("Written updated scene to " + scenePath);

  // Compile native Rive .riv binary
  const outRivPath = path.resolve(__dirname, "../mascots/owluko/owluko_pure_vector.riv");
  console.log("Compiling pure vector binary to " + outRivPath + "...");
  const createRes = await callMcpTool("riv_create", {
    outPath: outRivPath,
    scene: scene
  });

  if (createRes.isError) {
    console.error("Compilation error:", JSON.stringify(createRes, null, 2));
    process.exit(1);
  }

  const stat = fs.statSync(outRivPath);
  console.log(`Compiled pure vector .riv: ${stat.size} bytes (${(stat.size / 1024).toFixed(1)} KB)`);

  // Render Frame 0
  const frame0Path = path.resolve(__dirname, "../mascots/owluko/owluko_pure_vector_frame0.png");
  console.log("Rendering frame 0...");
  await callMcpTool("riv_render_frame", {
    path: outRivPath,
    outPath: frame0Path,
    animation: "idle",
    time: 0,
    background: "#FFFFFF"
  });

  // Render Blink Frame
  const frameBlinkPath = path.resolve(__dirname, "../mascots/owluko/owluko_pure_vector_blink.png");
  console.log("Rendering blink frame (t=1.3s)...");
  await callMcpTool("riv_render_frame", {
    path: outRivPath,
    outPath: frameBlinkPath,
    animation: "idle",
    time: 1.3,
    background: "#FFFFFF"
  });

  // Render Looping GIF
  const gifPath = path.resolve(__dirname, "../mascots/owluko/owluko_pure_vector.gif");
  console.log("Rendering 2.0s looping GIF...");
  await callMcpTool("riv_render_gif", {
    path: outRivPath,
    outPath: gifPath,
    animation: "idle",
    fps: 30,
    duration: 2.0,
    background: "#FFFFFF"
  });

  console.log("=== MASTER HAND-DRAWN OWLUKO COMPILED SUCCESSFULLY ===");
}

buildOwlukoMasterHanddrawnRive().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
